version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jtour-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - jtour-network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: jtour-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - jtour-network
    depends_on:
      - app


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jtour-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "8080:888"
    networks:
      - jtour-network
    depends_on:
      - mysql

  grafana:
    image: grafana/grafana:latest
    container_name: jtour-grafana
    restart: unless-stopped
    ports:
      - "3020:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - jtour-network
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: jtour-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - jtour-network

networks:
  jtour-network:
    driver: bridge

volumes:
  mysql-data:
  grafana-data:
  prometheus-data:
